import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

// Register PWA service worker (generated by vite-plugin-pwa)
if ('serviceWorker' in navigator) {
  import('virtual:pwa-register').then(({ registerSW }) => {
    registerSW({
      onNeedRefresh() {
        // New content available — auto-reload
        window.location.reload();
      },
      onOfflineReady() {
        console.log('✅ App ready to work offline');
      },
    });
  }).catch(() => {
    // In dev mode without the plugin built, this import will fail — that's fine
  });
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
